# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='accession_note',
            field=models.TextField(blank=True, help_text='Private note related to this accession'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='acquisition_method',
            field=models.CharField(choices=[('GIK', 'Gift In Kind'), ('TRN', 'Transfer'), ('PUR', 'Purchase'), ('OTH', 'Other')], default='GIK', max_length=3),
        ),
        migrations.AlterField(
            model_name='accession',
            name='anonymous_accession',
            field=models.BooleanField(help_text='Check if accession should be listed as anonymous on any public interface'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='date_paperwork_returned',
            field=models.DateField(blank=True, help_text='Date signed recipt of gift (ROG) was received', null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='date_paperwork_sent',
            field=models.DateField(blank=True, help_text='Date recipt of gift (ROG) was mailed out', null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='description',
            field=models.TextField(help_text='Publicly viewable description of the accession'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('PER', 'Person'), ('ORG', 'Organization')], default='PER', max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number_1',
            field=models.CharField(blank=True, help_text='Please use the following format: <em>(940) 391-0414</em>.', max_length=25),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number_2',
            field=models.CharField(blank=True, help_text='Please use the following format: <em>(940) 391-0414</em>.', max_length=25),
        ),
        migrations.AlterField(
            model_name='donor',
            name='salutation',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MISS', 'Miss'), ('MS', 'Ms.'), ('MRMRS', 'Mr. and Mrs.'), ('DR', 'Dr.')], max_length=5),
        ),
        migrations.AlterField(
            model_name='donor',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2),
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Designer Label'),
        ),
        migrations.AlterField(
            model_name='object',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex'), ('UnKn', 'Gender Unknown'), ('UnRec', 'Not Recorded'), ('NA', 'Not Applicable')], max_length=14),
        ),
        migrations.AlterField(
            model_name='object',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accession.Label', verbose_name='Designer Label'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_era',
            field=models.CharField(blank=True, choices=[('Pre-1770', 'Pre-1770'), ('1770-1779', '1770-1779'), ('1780-1789', '1780-1789'), ('1790-1799', '1790-1799'), ('1800-1809', '1800-1809'), ('1810-1819', '1810-1819'), ('1820-1829', '1820-1829'), ('1830-1839', '1830-1839'), ('1840-1849', '1840-1849'), ('1850-1859', '1850-1859'), ('1860-1869', '1860-1869'), ('1870-1879', '1870-1879'), ('1880-1889', '1880-1889'), ('1890-1899', '1890-1899'), ('1900-1909', '1900-1909'), ('1910-1919', '1910-1919'), ('1920-1929', '1920-1929'), ('1930-1939', '1930-1939'), ('1940-1949', '1940-1949'), ('1950-1959', '1950-1959'), ('1960-1969', '1960-1969'), ('1970-1979', '1970-1979'), ('1980-1989', '1980-1989'), ('1990-1999', '1990-1999'), ('2000-2009', '2000-2009'), ('2010-2019', '2010-2019')], max_length=10),
        ),
        migrations.AlterField(
            model_name='object',
            name='retailer_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accession.Retailer_Label', verbose_name='Retailer Label'),
        ),
        migrations.AlterField(
            model_name='retailer_label',
            name='retailer_label',
            field=models.CharField(max_length=200, unique=True, verbose_name='Retailer Label'),
        ),
    ]
